name: Docker Image CI/CD
on:
  push:
    branches: [ main ]
jobs:
  docker-compose:
    name: Docker-compose
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.HOST_USERNAME }}
          password: ${{ secrets.HOST_PASSWORD }}
          port: ${{ secrets.HOST_PORT }}
          script: |
            cd testActionsDockerCompose
            git pull origin
            docker-compose down
            docker-compose up -d

